/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspaceWorkspaceIdIndexRouteImport } from './routes/_app/workspace/$workspaceId/index'
import { Route as AppWorkspaceWorkspaceIdGroupGroupIdIndexRouteImport } from './routes/_app/workspace/$workspaceId/group/$groupId/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceWorkspaceIdIndexRoute =
  AppWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/workspace/$workspaceId/',
    path: '/workspace/$workspaceId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkspaceWorkspaceIdGroupGroupIdIndexRoute =
  AppWorkspaceWorkspaceIdGroupGroupIdIndexRouteImport.update({
    id: '/workspace/$workspaceId/group/$groupId/',
    path: '/workspace/$workspaceId/group/$groupId/',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspace/$workspaceId/': typeof AppWorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/group/$groupId/': typeof AppWorkspaceWorkspaceIdGroupGroupIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/group/$groupId': typeof AppWorkspaceWorkspaceIdGroupGroupIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/workspace/$workspaceId/': typeof AppWorkspaceWorkspaceIdIndexRoute
  '/_app/workspace/$workspaceId/group/$groupId/': typeof AppWorkspaceWorkspaceIdGroupGroupIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/group/$groupId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workspace/$workspaceId' | '/workspace/$workspaceId/group/$groupId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/workspace/$workspaceId/'
    | '/_app/workspace/$workspaceId/group/$groupId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspace/$workspaceId/': {
      id: '/_app/workspace/$workspaceId/'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId/group/$groupId/': {
      id: '/_app/workspace/$workspaceId/group/$groupId/'
      path: '/workspace/$workspaceId/group/$groupId'
      fullPath: '/workspace/$workspaceId/group/$groupId/'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdGroupGroupIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppWorkspaceWorkspaceIdIndexRoute: typeof AppWorkspaceWorkspaceIdIndexRoute
  AppWorkspaceWorkspaceIdGroupGroupIdIndexRoute: typeof AppWorkspaceWorkspaceIdGroupGroupIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppWorkspaceWorkspaceIdIndexRoute: AppWorkspaceWorkspaceIdIndexRoute,
  AppWorkspaceWorkspaceIdGroupGroupIdIndexRoute:
    AppWorkspaceWorkspaceIdGroupGroupIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
